sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hugodouma/docker-react -f Dockerfile.dev .

script: 
  -  docker run hugodouma/docker-react npm run test -- --coverage